# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_num', models.SmallIntegerField(verbose_name=b'Phase Number')),
                ('training', models.BooleanField(default=True)),
                ('passing_accuracy_percentage', models.SmallIntegerField(blank=True, null=True, verbose_name=b'Passing Accuracy %')),
                ('passing_time', models.DurationField(blank=True, null=True, verbose_name=b'Passing Time (ms)')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.DurationField(null=True)),
                ('modifier', models.BooleanField()),
                ('correct_response', models.PositiveSmallIntegerField()),
                ('given_response', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(editable=False)),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Phase')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('trials', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.BooleanField()),
                ('training', models.BooleanField()),
                ('correct_response', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Phase')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='SymbolSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block_size', models.SmallIntegerField()),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Phase')),
            ],
        ),
        migrations.AddField(
            model_name='symbol',
            name='symbol_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.SymbolSet'),
        ),
        migrations.AddField(
            model_name='singleset',
            name='option_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='hello.Symbol'),
        ),
        migrations.AddField(
            model_name='singleset',
            name='option_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='hello.Symbol'),
        ),
        migrations.AddField(
            model_name='singleset',
            name='option_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third', to='hello.Symbol'),
        ),
        migrations.AddField(
            model_name='singleset',
            name='stimulus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Symbol'),
        ),
        migrations.AddField(
            model_name='singleset',
            name='symbol_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.SymbolSet'),
        ),
        migrations.AddField(
            model_name='sessionlength',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Subject'),
        ),
        migrations.AddField(
            model_name='responseblock',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Subject'),
        ),
        migrations.AddField(
            model_name='responseblock',
            name='symbol_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.SymbolSet'),
        ),
        migrations.AddField(
            model_name='response',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.ResponseBlock'),
        ),
        migrations.AddField(
            model_name='response',
            name='option_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_response', to='hello.Symbol'),
        ),
        migrations.AddField(
            model_name='response',
            name='option_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_response', to='hello.Symbol'),
        ),
        migrations.AddField(
            model_name='response',
            name='option_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_response', to='hello.Symbol'),
        ),
        migrations.AddField(
            model_name='response',
            name='stimulus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Symbol'),
        ),
    ]
