# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='training',
        ),
    ]
