# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20160814_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus', models.CharField(max_length=1)),
                ('modifier', models.BooleanField(choices=[(True, b'!!!!!'), (False, b'?????')])),
                ('options', models.CharField(max_length=5)),
                ('training', models.BooleanField()),
                ('correct_response', models.CharField(max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='response',
            old_name='stimulus_type',
            new_name='modifier',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='responses',
            new_name='options',
        ),
        migrations.AddField(
            model_name='responseblock',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='symbolset',
            name='block_size',
            field=models.SmallIntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbolset',
            name='length',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbolset',
            name='phase',
            field=models.SmallIntegerField(choices=[(1, b'Phase 1 - Training'), (2, b'Phase 1 - Testing'), (3, b'Phase 2 - Training'), (4, b'Phase 2 - Testing'), (5, b'Phase 3 - Training'), (6, b'Phase 3 - Testing'), (7, b'Phase 4 - Training'), (8, b'Phase 4 - Testing'), (9, b'Phase 5 - Training'), (10, b'Phase 5 - Testing')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='correct_response',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='response',
            name='given_response',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='response',
            name='stimulus',
            field=models.CharField(max_length=1),
        ),
        migrations.AddField(
            model_name='singleset',
            name='symbol_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.SymbolSet'),
        ),
    ]
