# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160824_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseblock',
            name='training',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='training',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responseblock',
            name='phase',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='phase',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='symbolset',
            name='phase',
            field=models.SmallIntegerField(),
        ),
    ]
