# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20160824_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.ResponseBlock'),
        ),
        migrations.AlterField(
            model_name='response',
            name='given_response',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='modifier',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='singleset',
            name='modifier',
            field=models.BooleanField(),
        ),
    ]
