# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20160902_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseblock',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
