# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20161020_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='image',
            field=models.ImageField(upload_to=b'hello/static/hello'),
        ),
    ]
