# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_responseblock_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_id',
            field=models.SmallIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
