# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 19:40
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20161020_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
