# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20161012_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='passing_accuracy_percentage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='passing_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
